package com.aipro.upgrade.client;

import org.junit.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * {@link UpgradeConfig} 单元测试。
 * 覆盖：默认值、自定义 properties 覆盖、客户端 ID 持久化、当前版本读取。
 */
public class UpgradeConfigTest {

    /** 内置默认值校验。 */
    @Test
    public void defaults_whenNoConfigFile() throws IOException {
        Path workDir = createTempWorkDir();
        try {
            UpgradeConfig cfg = UpgradeConfig.load(workDir);
            assertEquals(UpgradeConfig.DEFAULT_SERVER_URL, cfg.getServerUrl());
            assertEquals(UpgradeStrategy.ASK, cfg.getStrategy());
            assertEquals(UpgradeConfig.DEFAULT_RETRY_MAX, cfg.getRetryMax());
            assertEquals(UpgradeConfig.DEFAULT_RETRY_BACKOFF_MS, cfg.getRetryBackoffMs());
            assertTrue(cfg.getDownloadDir().toString().contains("upgrade") && cfg.getDownloadDir().toString().contains("tmp"));
            assertTrue(cfg.getBackupDir().toString().contains("upgrade") && cfg.getBackupDir().toString().contains("backup"));
            assertEquals("", cfg.getSkipVersion());
            assertEquals("", cfg.getPromptImpl());
        } finally {
            deleteRecursively(workDir);
        }
    }

    /** 自定义 properties 覆盖默认值。 */
    @Test
    public void customProperties_overrideDefaults() throws IOException {
        Path workDir = createTempWorkDir();
        try {
            // 写入工作目录 upgrade.properties
            Properties p = new Properties();
            p.setProperty(UpgradeConfig.KEY_SERVER_URL, "http://10.0.0.5:8090");
            p.setProperty(UpgradeConfig.KEY_STRATEGY, "FORCE");
            p.setProperty(UpgradeConfig.KEY_RETRY_MAX, "5");
            p.setProperty(UpgradeConfig.KEY_RETRY_BACKOFF_MS, "3000");
            p.setProperty(UpgradeConfig.KEY_DOWNLOAD_DIR, "./upgrade/custom-tmp");
            p.setProperty(UpgradeConfig.KEY_BACKUP_DIR, "./upgrade/custom-backup");
            p.setProperty(UpgradeConfig.KEY_CURRENT_VERSION, "1.1.0");
            p.setProperty(UpgradeConfig.KEY_SKIP_VERSION, "1.5.0");
            p.setProperty(UpgradeConfig.KEY_PROMPT_IMPL, "com.example.MyPrompt");
            Path file = workDir.resolve(UpgradeConfig.CONFIG_FILE);
            try (java.io.OutputStream out = Files.newOutputStream(file)) {
                p.store(out, "test config");
            }

            UpgradeConfig cfg = UpgradeConfig.load(workDir);
            assertEquals("http://10.0.0.5:8090", cfg.getServerUrl());
            assertEquals(UpgradeStrategy.FORCE, cfg.getStrategy());
            assertEquals(5, cfg.getRetryMax());
            assertEquals(3000L, cfg.getRetryBackoffMs());
            // 统一用 / 分隔符比较路径后缀，避免 Windows 反斜杠差异
            String dl = cfg.getDownloadDir().toString().replace('\\', '/');
            String bk = cfg.getBackupDir().toString().replace('\\', '/');
            assertTrue("download dir 应以 upgrade/custom-tmp 结尾: " + dl, dl.endsWith("upgrade/custom-tmp"));
            assertTrue("backup dir 应以 upgrade/custom-backup 结尾: " + bk, bk.endsWith("upgrade/custom-backup"));
            assertEquals("1.1.0", cfg.getConfiguredCurrentVersion());
            assertEquals("1.5.0", cfg.getSkipVersion());
            assertEquals("com.example.MyPrompt", cfg.getPromptImpl());
        } finally {
            deleteRecursively(workDir);
        }
    }

    /** 非法策略值回退到默认 ASK。 */
    @Test
    public void invalidStrategy_fallsBackToAsk() throws IOException {
        Path workDir = createTempWorkDir();
        try {
            Properties p = new Properties();
            p.setProperty(UpgradeConfig.KEY_STRATEGY, "INVALID");
            Path file = workDir.resolve(UpgradeConfig.CONFIG_FILE);
            try (java.io.OutputStream out = Files.newOutputStream(file)) {
                p.store(out, "test");
            }
            UpgradeConfig cfg = UpgradeConfig.load(workDir);
            assertEquals(UpgradeStrategy.ASK, cfg.getStrategy());
        } finally {
            deleteRecursively(workDir);
        }
    }

    /** 客户端 ID 缺失时自动生成并持久化。 */
    @Test
    public void clientId_autogeneratedAndPersisted() throws IOException {
        Path workDir = createTempWorkDir();
        try {
            UpgradeConfig cfg1 = UpgradeConfig.load(workDir);
            String id1 = cfg1.getClientId();
            assertNotNull(id1);
            assertFalse(id1.isEmpty());

            // 再次加载应该取到同一个 ID（已写入配置文件）
            UpgradeConfig cfg2 = UpgradeConfig.load(workDir);
            String id2 = cfg2.getClientId();
            assertEquals(id1, id2);
        } finally {
            deleteRecursively(workDir);
        }
    }

    /** 当前版本优先读 version.json。 */
    @Test
    public void currentVersion_prefersVersionJson() throws IOException {
        Path workDir = createTempWorkDir();
        try {
            // 1. properties 中声明 1.0.0
            Properties p = new Properties();
            p.setProperty(UpgradeConfig.KEY_CURRENT_VERSION, "1.0.0");
            Path file = workDir.resolve(UpgradeConfig.CONFIG_FILE);
            try (java.io.OutputStream out = Files.newOutputStream(file)) {
                p.store(out, "test");
            }
            UpgradeConfig cfg1 = UpgradeConfig.load(workDir);
            assertEquals("1.0.0", cfg1.getCurrentVersion());

            // 2. 写入 version.json，应优先取此版本
            String versionJson = "{\"version\":\"1.5.0\",\"sha256\":\"abc\",\"updatedAt\":\"2026-09-28T10:15:30+08:00\"}";
            Files.write(workDir.resolve(UpgradeConfig.VERSION_FILE),
                    versionJson.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            UpgradeConfig cfg2 = UpgradeConfig.load(workDir);
            assertEquals("1.5.0", cfg2.getCurrentVersion());
        } finally {
            deleteRecursively(workDir);
        }
    }

    /** version.json 损坏时回退到配置项。 */
    @Test
    public void currentVersion_corruptVersionJson_fallsBackToConfig() throws IOException {
        Path workDir = createTempWorkDir();
        try {
            Properties p = new Properties();
            p.setProperty(UpgradeConfig.KEY_CURRENT_VERSION, "2.0.0");
            Path file = workDir.resolve(UpgradeConfig.CONFIG_FILE);
            try (java.io.OutputStream out = Files.newOutputStream(file)) {
                p.store(out, "test");
            }
            Files.write(workDir.resolve(UpgradeConfig.VERSION_FILE),
                    "not json".getBytes(java.nio.charset.StandardCharsets.UTF_8));
            UpgradeConfig cfg = UpgradeConfig.load(workDir);
            assertEquals("2.0.0", cfg.getCurrentVersion());
        } finally {
            deleteRecursively(workDir);
        }
    }

    // ===== 测试辅助 =====

    private Path createTempWorkDir() throws IOException {
        Path dir = Files.createTempDirectory("upgrade-cfg-test-");
        return dir;
    }

    private void deleteRecursively(Path dir) throws IOException {
        if (!Files.exists(dir)) {
            return;
        }
        Files.walkFileTree(dir, new java.nio.file.SimpleFileVisitor<Path>() {
            @Override
            public java.nio.file.FileVisitResult visitFile(Path file, java.nio.file.attribute.BasicFileAttributes attrs)
                    throws IOException {
                Files.deleteIfExists(file);
                return java.nio.file.FileVisitResult.CONTINUE;
            }

            @Override
            public java.nio.file.FileVisitResult postVisitDirectory(Path d, IOException exc) throws IOException {
                Files.deleteIfExists(d);
                return java.nio.file.FileVisitResult.CONTINUE;
            }
        });
    }
}
